apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tke-extend-network-controller
  name: tke-extend-network-controller-selfsigned-issuer
  namespace: kube-system
spec:
  selfSigned: {}

