apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tke-extend-network-controller.fullname" . }}-env
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "tke-extend-network-controller.labels" . | nindent 4 }}
type: Opaque
stringData:
  REGION: '{{ required "A valid .region required!" .Values.region }}'
  SECRET_ID: '{{ required "A valid .secretID required!" .Values.secretID }}'
  SECRET_KEY: '{{ required "A valid .secretKey required!" .Values.secretKey }}'
  VPCID: '{{ required "A valid .vpcID required!" .Values.vpcID }}'
  CLUSTER_ID: '{{ required "A valid .clusterID required!" .Values.clusterID }}'
