apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: tke-extend-network-controller
    control-plane: tke-extend-network-controller
  name: {{ include "tke-extend-network-controller.fullname" . }}
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    control-plane: tke-extend-network-controller
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: tke-extend-network-controller
  name: {{ include "tke-extend-network-controller.fullname" . }}-webhook-service
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    control-plane: tke-extend-network-controller

