apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tke-extend-network-controller
  name: tke-extend-network-controller
  namespace: kube-system

