apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: kube-system/tke-extend-network-controller-serving-cert
  name: tke-extend-network-controller-mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: tke-extend-network-controller-webhook-service
      namespace: kube-system
      path: /mutate-networking-cloud-tencent-com-v1alpha1-dedicatedclblistener
  failurePolicy: Fail
  name: mdedicatedclblistener.kb.io
  rules:
  - apiGroups:
    - networking.cloud.tencent.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - dedicatedclblisteners
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: kube-system/tke-extend-network-controller-serving-cert
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/created-by: tke-extend-network-controller
    app.kubernetes.io/instance: validating-webhook-configuration
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: validatingwebhookconfiguration
    app.kubernetes.io/part-of: tke-extend-network-controller
  name: tke-extend-network-controller-validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: tke-extend-network-controller-webhook-service
      namespace: kube-system
      path: /validate-networking-cloud-tencent-com-v1alpha1-dedicatedclblistener
  failurePolicy: Fail
  name: vdedicatedclblistener.kb.io
  rules:
  - apiGroups:
    - networking.cloud.tencent.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - dedicatedclblisteners
  sideEffects: None

