---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-networking-cloud-tencent-com-v1alpha1-clbpodbinding
  failurePolicy: Fail
  name: mclbpodbinding.kb.io
  rules:
  - apiGroups:
    - networking.cloud.tencent.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clbpodbindings
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-networking-cloud-tencent-com-v1alpha1-clbpodbinding
  failurePolicy: Fail
  name: vclbpodbinding.kb.io
  rules:
  - apiGroups:
    - networking.cloud.tencent.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clbpodbindings
  sideEffects: None
