# permissions for end users to view dedicatedclbservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: tke-extend-network-controller
    app.kubernetes.io/managed-by: kustomize
  name: dedicatedclbservice-viewer-role
rules:
- apiGroups:
  - networking.cloud.tencent.com
  resources:
  - dedicatedclbservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.cloud.tencent.com
  resources:
  - dedicatedclbservices/status
  verbs:
  - get
