---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tke-extend-network-controller-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - networking.cloud.tencent.com
  resources:
  - dedicatedclblisteners
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.cloud.tencent.com
  resources:
  - dedicatedclblisteners/finalizers
  verbs:
  - update
- apiGroups:
  - networking.cloud.tencent.com
  resources:
  - dedicatedclblisteners/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.cloud.tencent.com
  resources:
  - dedicatedclbservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.cloud.tencent.com
  resources:
  - dedicatedclbservices/finalizers
  verbs:
  - update
- apiGroups:
  - networking.cloud.tencent.com
  resources:
  - dedicatedclbservices/status
  verbs:
  - get
  - patch
  - update
