---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - networking.cloud.tencent.com
  resources:
  - dedicatedclbservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.cloud.tencent.com
  resources:
  - dedicatedclbservices/finalizers
  verbs:
  - update
- apiGroups:
  - networking.cloud.tencent.com
  resources:
  - dedicatedclbservices/status
  verbs:
  - get
  - patch
  - update
