apiVersion: networking.cloud.tencent.com/v1alpha1
kind: DedicatedCLBListener
metadata:
  labels:
    app.kubernetes.io/name: tke-extend-network-controller
    app.kubernetes.io/managed-by: kustomize
  name: dedicatedclblistener-sample
spec:
  lbId: lb-xxx # 必选，clb的id
  lbRegion: ap-chengdu # 可选，clb所在地域，默认为集群所在地域
  lbPort: 8088 # 必选，监听器端口
  protocol: TCP # 必选，监听器协议。TCP | UDP | HTTP | HTTPS | TCP_SSL | QUIC
  listenerConfig: clblistenerconfig-sample # 可选，创建监听器的配置
  dedicatedTarget: # 可选，需要绑定独占rs时指定
    ip: 172.16.17.32 # 必选，目标ip
    port: 8088 # 必选，目标端口
