apiVersion: networking.cloud.tencent.com/v1apha1
kind: DedicatedCLBService
metadata:
  namespace: demo
  name: dedicatedclbservice-sample
  labels:
    app.kubernetes.io/name: tke-extend-network-controller
    app.kubernetes.io/managed-by: kustomize
spec:
  lbRegion: ap-chengdu # 可选，CLB 所在地域，默认为集群所在地域
  selector: # 必选，pod 的 label 选择器，会为每个被选中的pod 自动分配一个CLB的监听器。
    app: gameserver
  lbPortRange: # 必选，在CLB自动创建监听器，每个Pod占用一个端口，下面示例端口号范围在 500-600
    min: 500
    max: 600
  ports: # 必选，自动创建的CLB监听器与后端pod端口的映射关系与自动创建的监听器配置
    - listenerConfig: clblistenerconfig-sample-tcp # 必选，CLB 监听器配置，必须为已存在的 CLBListenerConfig 资源。
      targetPort: 9000 # 容器监听的端口
    - listenerConfig: clblistenerconfig-sample-udp
      targetPort: 8000
  existedLbIds: # 复用已有的 CLB 实例，指定 CLB 实例 ID 的列表
    - lb-xxx
    - lb-yyy
    - lb-zzz
  lbAutoCreate:
    enable: true # 当 CLB 不足时，是否自动创建 CLB
    extensiveParameters: | # 指定购买 CLB 的参数(JSON 字符串格式)：按流量计费，带宽上限 2048 Mbps （完整参数列表参考 CreateLoadBalancer 接口 https://cloud.tencent.com/document/api/214/30692）
      {
        "InternetAccessible": {
          "InternetChargeType": "TRAFFIC_POSTPAID_BY_HOUR",
          "InternetMaxBandwidthOut": 2048
        }
      }
